[tool.poetry]
name = "autoenum"
version = "0.1.0"
description = ""
authors = ["Matt Jones <matt.jones@symphona.us>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-libnmap = "^0.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
